name: Push static to io

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  deploy:
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
    with:
      skip-build: true
