name: Uplift all vocabulary files

on:
  workflow_dispatch:

jobs:
  uplift-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengeospatial/ogc-na-tools.git
      - name: Process files
        run: |
          #find . -name '*.csv' | while read CSV_FILE; do python -m ogc.na.ingest_json \
          #           --skip-on-missing-context --json-ld --context csv2python.yml "${CSV_FILE}" > "${CSV_FILE}.json"
          #          done
          python -m ogc.na.ingest_json --batch --all --skip-on-missing-context \
            --json-ld --ttl --work-dir . --domain-config .ogc/catalog.ttl
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Semantic uplift of all vocabulary source files"
          default_author: github_actions
